### ISSUE TITLE
非常棒

### ISSUE THREAD

**Issue by phpyii** [HADB/GetWeixinCode#1]
很好用赞一个

**Comment by rainforyou** [comment]
怎么用？我想把几个第三方都整合起来，如果不是自定义开发的话就不能用对吧

**Comment by phpyii** [comment]
作者说的很清楚啊，你用开发者模式把授权域名设置下，然后把这个html放到授权域名下，获取code的时候就不用访问腾讯的地址了，直接访问这个地址就ok了

**Comment by rainforyou** [comment]
还是不太明白，求告知QQ或者群指导下

**Comment by lzlshow** [comment]
现在好像还是不行，用这种方法还是不行
