### ISSUE TITLE
域名校验问题

### ISSUE THREAD

**Issue by YouweiYao** [HADB/GetWeixinCode#16]
你好，在看微信公众号的文档中看到下面着一条：
尤其注意：由于公众号的secret和获取到的access_token安全级别都非常高，必须只保存在服务器，不允许传给客户端。后续刷新access_token、通过access_token获取用户信息等步骤，也必须从服务器发起。
目前手头没有服务号可以进行测试，请问微信是否会对用code和appsecret换取openid这个接口的发起服务器域名进行校验。比如绑定了abc.com，最后是xyz.com的服务器发起请求获取access_token

**Comment by HADB** [comment]
会校验。我们这个项目只是从多个域名都统一使用一个域名去获得code，至于code换取openid这个必须在后端去做处理的。
