### ISSUE TITLE
可以说一下具体的参数如何写吗？

### ISSUE THREAD

**Issue by lzlshow** [HADB/GetWeixinCode#2]
想不通是如何用的，需要提交两次参数还是如何，实在有点乱！
望HADB可以回答一下，谢谢！

**Comment by HADB** [comment]
1、在abc.com域名下放置get-weixin-code.html文件
2、在代码中这样使用
`location.href = 'http://abc.com/get-weixin-code.html?appid=XXX&scope=XXX&state=XXX&redirect_uri=' + encodeURIComponent(location.href);`
