### ISSUE TITLE
授权地址暴露问题

### ISSUE THREAD

**Issue by ismartinliu** [HADB/GetWeixinCode#20]
如果此地址被用户手机访问授权地址暴露，很可能会让他人恶意使用授权访问。可以在跳转处加些主机名访问控制。

**Comment by HADB** [comment]
通过授权获取的code，还需要经过进一步的操作才可以获取到access_token，所以即便别人拿到了你的code，也没有用。可以在后端做校验的时候过滤掉白名单外的请求。

**Comment by ismartinliu** [comment]
对，这样操作也可以，避免授权页依赖过多的配置。
