### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by ronaldoooo** [HADB/GetWeixinCode#21]
有一个问题，在微信做完授权重定向回来的请求，怎么拉得到之前设置的redirect_uri呢？看代码，else里面直接获取到了redirect_uri. 总感觉有问题呀。

**Comment by HADB** [comment]
@ronaldoooo else里面的redirect_uri是我们自己传进去的，所以一直在，只是把从微信里面拿到的code拼进去了。你可以用一下。并没有问题。
