### ISSUE TITLE
跳转到的url如果有多个参数的话，只能传第一个

### ISSUE THREAD

**Issue by yeahugo** [HADB/GetWeixinCode#22]
例如下面的url， 
`http://dev.order.panpom.com/code/get-weixin-code.html?appid=wx8576fc5a32db3fa0&scope=snsapi_base&state=hello-world&redirect_uri=http://h.93pk.com?Im=abc&gourl=123` 
实际跳转地址是 `http://h.93pk.com/?Im=abc&code=081WYLou0QXK6f1uQhpu0yH2pu0WYLot&state=hello-world` ,缺少gourl参数

**Comment by HADB** [comment]
redirect_uri中的内容需要encodeURIComponent一下
