### ISSUE TITLE
请教一个微信开发问题

### ISSUE THREAD

**Issue by ljt7560868** [HADB/GetWeixinCode#23]
通过微信公众号  菜单 跳转到其他域名的页面时 出现空白页面问题  跳转授权回调页面 是没问题的 但是其他域名的页面 都是空白页面 如www.baidu.com     请问这种情况如何解决？

**Comment by HADB** [comment]
没有太明白你说的意思

**Comment by ljt7560868** [comment]
微信菜单 跳转到后台后 然后sendRedirect 其他域名的页面 这种情况   能否添加一下微信请教一下？

**Comment by HADB** [comment]
其他域名的页面就按照我们这个方式来做跳转就可以了，直接用你绑定的域名多做一次跳转，具体使用方式可以参照README中的代码。
