### ISSUE TITLE
redirectUrl中参数问题

### ISSUE THREAD

**Issue by alex521** [HADB/GetWeixinCode#24]
如果在redirecturl中带有额外的参数，&符号，好象就会报错，appid参数错误，不知道什么原因，redirecturl已经encode过

**Comment by alex521** [comment]
因为是单页应用，url中还有#号

**Comment by HADB** [comment]
encode过应该是没问题的，可以把你的redirectUrl贴出来看下

**Comment by mm7894215** [comment]
我也遇到这个问题，redirectUrl报错，，
http://ielts.easyautumn.com/get-weixin-code.html?appid=wxfa243f707ebc8cac&redirect_uri=http%3a%2f%2fdev.www.papaen.com%2fofficialWebsiteMobile%2findex.htmlscope=snsapi_base&state=123#wechat_redirect

**Comment by HADB** [comment]
你后面scope=snsapi_base&state=123#wechat_redirect这个是有问题的，这些应该都在redirect_url中，并且做encode
