### ISSUE TITLE
嵌入公众号问题

### ISSUE THREAD

**Issue by mm7894215** [HADB/GetWeixinCode#27]
使用这个方法嵌入公众号菜单栏，菜单栏1（abc.html）、菜单栏2（def.html）.
使用这个方法现在打开菜单栏1就无法打开菜单栏2. 同理打开2 ，就无法打开1

**Comment by mm7894215** [comment]
@HADB 大佬来看下哦！

**Comment by HADB** [comment]
理论上不会有这个问题，能给下详细使用方式和地址吗？估计是url转义有问题
