### ISSUE TITLE
redirect_url 多参数的情况是不是不适用呢

### ISSUE THREAD

**Issue by haohexin** [HADB/GetWeixinCode#30]
在www.abc.com域名下部署get-weixin-code.html
需要获取微信授权 的地址是 `http://www.xyz.com/index.php?a=3&b=4`

这时候 
`http://www.abc.com/xxx/get-weixin-code.html?appid=XXXX&scope=snsapi_base&state=hello-world&redirect_uri=http%3A%2F%2Fwww.xyz.com%2Findex.php%3Fa%3D326%b%3D4`

这样就提示 redirect_url 参数错误

**Comment by HADB** [comment]
你这个redirect_uri本身格式有问题，你可以试下：decodeURIComponent("http%3A%2F%2Fwww.xyz.com%2Findex.php%3Fa%3D326%b%3D4")

**Comment by haohexin** [comment]
谢谢大佬
`http%3A%2F%2Fwx.llxtd.com%2Fapp%2Findex.php%3Fi%3D3%26t%3D3`
decode 出来是
`http://wx.llxtd.com/app/index.php?i=3&t=3`
然后 补全所有的地址
`http://fwh.llxtd.com/get-weixin-code.html?appid=wx97388116af6c38ef&scope=snsapi_base&state=hello-world&redirect_uri=http%3A%2F%2Fwx.llxtd.com%2Fapp%2Findex.php%3Fi%3D3%26t%3D3`
在微信web开发工具中访问这个地址就是显示 redirect_url 参数错误,链接被重定向成
`https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx97388116af6c38ef&redirect_uri=http%3A%2F%2Fwx.llxtd.com%2Fapp%2Findex.php%3Fi%3D3%26j%3D3%26c%3Dauth%26a%3Doauth%26scope%3Dsnsapi_base&response_type=code&scope=snsapi_base&state=we7sid-3a6f1a378b1196e857f9aad1f33845d8&uin=MjAyMjM3ODM0MA%3D%3D&key=acf9e0498e32d7d7598a567a21247f76720f0146b3c5a9e78933e97aea2a92e5f09095b14ce5c4a02081e79933b8d846&pass_ticket=Y1QBya5RO28DSIv/QyeipkJTPbIftki2ayhxu3ri167NMl2wU5ZhSk8QIQsEIxGWrVkR8+RaBHVmuWLzmOs9+g==`

**Comment by HADB** [comment]
很奇怪的是，你在微信开发工具中里面redirect_uri的地址decode出来是：
`http://wx.llxtd.com/app/index.php?i=3&j=3&c=auth&a=oauth&scope=snsapi_base`，你传进去的应该是`http://fwh.llxtd.com/get-weixin-code.html?appid=wx97388116af6c38ef&scope=snsapi_base&state=hello-world&redirect_uri=http%3A%2F%2Fwx.llxtd.com%2Fapp%2Findex.php%3Fi%3D3%26t%3D3`这个url encode之后的地址

**Comment by HADB** [comment]
奇怪的是，你这个微信开发工具中的redirect_uri decode出来是
```
http://wx.llxtd.com/app/index.php?i=3&j=3&c=auth&a=oauth&scope=snsapi_base
```
理论上，应该是
```
http%3A%2F%2Ffwh.llxtd.com%2Fget-weixin-code.html%3Fappid%3Dwx97388116af6c38ef%26scope%3Dsnsapi_base%26state%3Dhello-world%26redirect_uri%3Dhttp%253A%252F%252Fwx.llxtd.com%252Fapp%252Findex.php%253Fi%253D3%2526t%253D3
```

**Comment by haohexin** [comment]
嗯 这个很奇怪  还有一个奇怪的是
`[](http://wx.llxtd.com/app/index.php?i=3&t=3)`
这个地址直接在浏览器可以访问 哈哈 并没有提示必须在微信中打开
