### ISSUE TITLE
二次获取access_token问题

### ISSUE THREAD

**Issue by caorenjie** [HADB/GetWeixinCode#31]
在get-weixin-code.html中获取到了code这是没问题的，但第二次获取access_token的时候需要appid和secret,这两个都是在get-weixin-code这个项目认证后所固定的，也就是说其他系统需要写死这两个值，为何不在get-weixin-code.html中拿到code之后直接去请求access_token再把信息传递回来

**Comment by HADB** [comment]
获取access_token的操作在前端很不安全，会暴露secret，这个操作肯定要放到后端去获取的。
