### ISSUE TITLE
此rep是初衷是为了解决微信公众号回调域名仅切只有一个的问题？存疑 ：）

### ISSUE THREAD

**Issue by br2me** [HADB/GetWeixinCode#35]
clone下来看了看，对于代码的实现具体了然于心，其部署还是不太了解，可行性存疑
'redirect_uri': encodeURIComponent(location.href) 在未获取到code的情况下，中间站拿到的当前域名的uri，而在具体做跳转到微信那边也会对redirect_uri进行检测是否匹配你所在平台配置的域名，而在else回来的时候自然也是行不通的，微信公众号对其开发者提供了state值，可任意传递值，可在此参数进行各个子业务的区分然而对code进行充分的加盐加密回调各自业务系统；水准不佳若有误解、还望见谅多交流。

**Comment by HADB** [comment]
微信只能配置一个安全域名，所以必然得配置中间页所在的域名，也就是将中间页配置在安全域名下。
由该中间页获取到code之后跳转至同一个公众号下其他需要OAuth认证的域名。对于微信来说，他们看到的永远只是中间页在获取认证，跟其他页面没有关系，跳转都是中间页获取到code之后再进行跳转的。
目前已经经过广泛使用，可行性已经经过大量认证了，不必存疑。

**Comment by HADB** [comment]
这个功能可以根据需求自定义添加
