### ISSUE TITLE
是不是不支持用了cdn和强制性跳转到https的网站？

### ISSUE THREAD

**Issue by zhujitop** [HADB/GetWeixinCode#38]
比如我授权域名是：www.git.com ，网站A。
另外个域名是：test.git.com，网站B。
我在网站B里面把授权代码的读取链接改成了：https://www.git.com/get-weixin-code?appid=
这个时候访问test.git.com，会出现反复登录的问题，一直循环。

网站B test.git.com做了https强制性跳转。
或者是没改对代码？

原来网站b的授权代码是：
	public function getOauthCodeUrl($callback, $state = '') {
		return "https://open.weixin.qq.com/connect/oauth2/authorize?appid={$this->account['key']}&redirect_uri={$callback}&response_type=code&scope=snsapi_base&state={$state}#wechat_redirect";
	}
改成了：
	public function getOauthCodeUrl($callback, $state = '') {
		return "https://www.git.com/get-weixin-code?appid={$this->account['key']}&redirect_uri={$callback}&response_type=code&scope=snsapi_base&state={$state}#wechat_redirect";
	}

**Comment by HADB** [comment]
从描述中暂时无法定位问题，应该与你们目前的系统处理有关。希望能够提出与本项目相关的问题。
