### ISSUE TITLE
第二次腾讯回调时候，怎么还有redirect_uri这个参数？

### ISSUE THREAD

**Issue by zhaoyou** [HADB/GetWeixinCode#40]
你好，感谢你的技术方案，有个地方一直没有想明白。第二次腾讯回调到中间授权页面时，怎会还有这个`direct_uri` 这个参数呢？这个参数应该是第一次真正的应用带过来的，中间调用腾讯的时候，回调已经手动改成中间代理的地址了`location.href`。页面都刷新了。怎么还有一个前面那个参数？实在想不明白。希望不吝解释下。

![wechatimg37](https://user-images.githubusercontent.com/612257/45795796-12d57a80-bcd0-11e8-9811-da8bdaab52ef.jpeg)

**Comment by jonnywang** [comment]
获取你自己的网址，拼接code,state，最终 location.href = "http://你自己的/ ?code=xxx&state=xxxx"

**Comment by zhaoyou** [comment]
> 获取你自己的网址，拼接code,state，最终 location.href = "[http://你自己的/](http://%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84/) ?code=xxx&state=xxxx"

@jonnywang 应该是你这个意思， 最终的回调地址应该是自己拼接返回去，由于有多个地方调用，所以返回的地址应该不能固定，应该根据state去判断或者其他方式，我只是好奇为什么 GWC.urlParams['redirect_uri'] 代码这样可以？

**Comment by randleea** [comment]
GWC.urlParams['redirect_uri'] 为什么拿到的都是undefined

**Comment by qaqRose** [comment]
@zhaoyou  第一次进入`get-weixin-code.html`页面的时候, 带的`redirect_uri`参数 被包含在` location.href`中发送给微信了,所以在微信回调地址中,依然保留者`redirect_uri`参数
