### ISSUE TITLE
能不能再具体点，我还是不知道如何来设置

### ISSUE THREAD

**Issue by snsnsjsn** [HADB/GetWeixinCode#8]
比如，我有一个域名为 aaa.com 然后这个域名指向一个网站A，我又用 bbb.aaa.com二级域名指向另外一个独立的网站B。

然后我如果设置授权域名为  bbbb.aaa.com则 网站B的回调地址 http://bbbb.aaa.com/xxx/xxx/xxxx.php可以完成。

如果我设置授权域名为 aaa.com则网站B提示 redirect_uri参数错误。

我如果把你的提供文件get-weixin-code.html 放在 aaa.com网站A的根目录。那么接下来如何设置？？

**Comment by HADB** [comment]
授权域名首先设置为一个，可以是bbbb.aaa.com或者aaa.com，例如你设置成了aaa.com，那么你把get-weixin-code.html放置到aaa.com下，以后的回调都是通过调用aaa.com/get-weixin-code.html这个页面来完成，不再调用微信的回调地址了。是需要自己修改从微信授权的那部分的代码的，如果是第三方的应用是不行的。你按照我的步骤一步一步来肯定没问题，已经非常详细了。

**Comment by snsnsjsn** [comment]
嗯，自己摸索，谢谢回复！

2016-08-08 13:46 GMT+08:00 Bean Deng 邓斌 <notifications@github.com>:
