### ISSUE TITLE
资源引用

### ISSUE THREAD

**Issue by JeffreySu** [HADB/GetWeixinCode#9]
Hi，您好，我是Senparc.Weixin SDK的作者，最近在整理一些微信开发的资源，计划将这个功能下周收录到https://github.com/JeffreySu/WeixinResource，署名和版权信息我们都会保留。

如果有任何问题请联系我，谢谢！

**Comment by HADB** [comment]
@JeffreySu 非常荣幸！PS：我也是Senparc.Weixin SDK的忠实用户！

**Comment by JeffreySu** [comment]
谢谢：）

**Comment by JeffreySu** [comment]
已发布：
https://github.com/JeffreySu/WeixinResource/blob/master/%E5%AD%A6%E4%B9%A0%E8%B5%84%E6%BA%90/20160825-%E8%A7%A3%E5%86%B3%E5%BE%AE%E4%BF%A1OAuth2.0%E7%BD%91%E9%A1%B5%E6%8E%88%E6%9D%83%E5%8F%AA%E8%83%BD%E8%AE%BE%E7%BD%AE%E4%B8%80%E4%B8%AA%E5%9B%9E%E8%B0%83%E5%9F%9F%E5%90%8D%E7%9A%84%E9%97%AE%E9%A2%98.md
